version: '3'

services:
  openldap:
    image: zentekmx/openldap:latest
    ports:
    - "389:389"
    volumes:
    - ${OPENLDAP_VOLUME:-openldap-volume}:/var/lib/ldap:Z

  mysql:
    image: mysql:5.7
    volumes:
    - ${MYSQL_VOLUME:-mysql-volume}:/var/lib/mysql:Z
    environment:
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DB}

  joomla:
    image: joomla
    links:
    - mysql
    depends_on:
    - mysql
    ports:
    - 8080:80
    environment:
    - JOOMLA_DB_HOST=mysql
    - JOOMLA_DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - ${JOOMLA_VOLUME:-joomla-volume}:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    links:
    - mysql
    depends_on:
    - mysql
    ports:
    - "8090:80"
    environment:
    - PMA_HOST=mysql

volumes:
  mysql-volume:
  joomla-volume:
